# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f9a1d927aa77b45e01b4e8a7379613a543f2f5262b7f8e999f1966d49afffb2e64b76654670b6628cc094650f68a716609934aea2cdc9ff71a50d762cea835a

test:
  secret_key_base: 135bce0515d8c484d25f097548e22bb26ba743764ad149b3fb630768e735cd470f502484d7e9316bb3913a40e62af4e5bae83af3080f554442713dfc40c4a429

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
